export type Question = {
  id?: string; // id is optional as it's generated by react-hook-form on the client
  question: string;
  options: string[];
  answer: string;
  type: 'multiple_choice' | 'true_false' | 'short_answer';
};

export type Quiz = {
  id: string;
  title: string;
  questions: Omit<Question, 'id'>[];
  createdAt?: any; 
};
